### ISSUE TITLE
Exemplo de Produtos e Serviços retorna "O conteúdo retornado pelo endpoint não possui um JSON válido." 

### ISSUE THREAD

**Issue by supermuka** [knuppe/openbankingbr#1]
Considerando a execução deste exemplo:

```
from openbankingbr import OpenBankingBR

ob = OpenBankingBR(cacheDir='./cache')

for participante in ob.participantes:
    print(f'Participante: {participante.nome}')
    for produto in participante.produtos:
        print(f'Produto: {produto.tipo} - {produto.nome}')

        # Serviços disponíveis no produto
        for servico in produto.servicos:
            print(f'    Serviço > {servico.nome}')

        # Pacotes de serviço disponíveis no produto.
        for pacote in produto.pacotes:
            print(f'    Pacote > {pacote.nome}')
```

O seguinte erro ocorre:

> Traceback (most recent call last):
>   File "D:\Levius\IdeaProjects\open-finance\products-services.py", line 7, in <module>
>     for produto in participante.produtos:
>   File "C:\Users\samue\AppData\Local\Programs\Python\Python39\lib\site-packages\openbankingbr\models.py", line 165, in produtos
>     for page in fetchUrlPages(endPoint, self.openBaking.cacheDir):
>   File "C:\Users\samue\AppData\Local\Programs\Python\Python39\lib\site-packages\openbankingbr\utils.py", line 155, in fetchUrlPages
>     root = fetchUrl(url, cacheDir = cacheDir)
>   File "C:\Users\samue\AppData\Local\Programs\Python\Python39\lib\site-packages\openbankingbr\utils.py", line 145, in fetchUrl
>     raise OpenBankingException("O conteúdo retornado pelo endpoint não possui um JSON válido.") from None
> openbankingbr.errors.OpenBankingException: O conteúdo retornado pelo endpoint não possui um JSON válido.

**Comment by knuppe** [comment]
O problema acontece com a url https://api.sulcrediouro.com.br/open-banking/products-services/v1/personal-accounts retorna um 404 NotFound, o que causa o erro que você identificou. Vou subir uma versão que ignora os dados quando a api da financeira não está funcionando como deveria.

**Comment by knuppe** [comment]
Publiquei a versão corrigida, só atualizar que deve funcionar.

```bash
python3 -m pip install --upgrade openbankingbr
```
